name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npx tsp format **/*.tsp
      - run: git diff
      - run: |
          git status --porcelain
          git diff --no-ext-diff --quiet --exit-code
        name: Check not out of date generated files
  build2:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: git clone https://github.com/azure/azure-rest-api-specs && cd ./azure-rest-api-specs && git checkout 622891e1923a4fd9501263d1c14da7f040c1b1f2
      - run: npm ci
        working-directory: azure-rest-api-specs
      - run: npx tsp format **/*.tsp
        working-directory: azure-rest-api-specs/specification/cognitiveservices
      - run: git diff
      - run: |
          git status --porcelain
          git diff --no-ext-diff --quiet --exit-code
        name: Check not out of date generated files
        working-directory: azure-rest-api-specs

